### ISSUE TITLE
【后台管理】要有分级权限管理

### ISSUE THREAD

**Issue by shuohanw** [xingshidongman/qiao-parent#42]
要有分级权限管理：站长管理主要分级权限授权。族人注册后进入家谱编修状态，谁录入谁有权浏览、修改、导出，其他人无权。编辑以上后台管理，浏览、修改、导出，需获得区域授权。这一块我没找到

**Comment by minikiller** [comment]
后台管理系统有完整的权限控制，可以授权到按钮，同时具有数据权限的功能，分别可以设置四种分级数据访问权限。
