### ISSUE TITLE
【后台管理】浏览器兼容

### ISSUE THREAD

**Issue by moyangdongnuan** [xingshidongman/qiao-parent#53]
谷歌浏览器
![1531787574 1](https://user-images.githubusercontent.com/38937486/42790217-67e5cb86-899c-11e8-940b-0a55968c6525.png)

IE浏览器
![1531787607 1](https://user-images.githubusercontent.com/38937486/42790218-684e4f8a-899c-11e8-93dc-788280f0f495.png)

**Comment by juezhan** [comment]
用户登录超时造成的。
